// Junguian Archetypes - Extended Version
export const ARCHETYPES = [
  {
    key: 'innocent',
    name: 'Inocente',
    nameEn: 'The Innocent',
    motto: 'Livre para ser você mesmo',
    color: '#fef3c7',
    icon: '🕊️',
    focus: ['spiritual', 'personal'],
    description: 'Busca a felicidade através da simplicidade e otimismo',
    fullDescription: 'O Inocente acredita na bondade inerente da vida e das pessoas. Busca criar um paraíso através de pureza, fé e otimismo. Este arquétipo valoriza a simplicidade, a autenticidade e a liberdade de ser quem realmente é, sem máscaras ou pretensões.',
    strengths: ['Fé', 'Otimismo', 'Entusiasmo', 'Lealdade', 'Simplicidade'],
    weaknesses: ['Negação', 'Ingenuidade', 'Dependência', 'Medo de punição'],
    desire: 'Experimentar o paraíso',
    fear: 'Fazer algo errado e ser punido',
    strategy: 'Fazer as coisas certas',
    gift: 'Fé e otimismo',
    shadow: 'Negação e dependência'
  },
  {
    key: 'explorer',
    name: 'Explorador',
    nameEn: 'The Explorer',
    motto: 'Não me limite',
    color: '#d1fae5',
    icon: '🧭',
    focus: ['physical', 'cultural'],
    description: 'Busca liberdade através de aventura e descoberta',
    fullDescription: 'O Explorador busca uma vida mais autêntica e plena através da descoberta do mundo exterior e interior. Não suporta limites, rotinas ou conformismo. Sua jornada é sobre encontrar a si mesmo explorando novas experiências, lugares e ideias.',
    strengths: ['Autonomia', 'Ambição', 'Autenticidade', 'Coragem', 'Honra'],
    weaknesses: ['Perambular sem rumo', 'Não se encaixar', 'Inquietação', 'Alienação'],
    desire: 'Liberdade para descobrir a si mesmo',
    fear: 'Ficar preso, conformidade',
    strategy: 'Buscar e experimentar coisas novas',
    gift: 'Autonomia e autenticidade',
    shadow: 'Alienação e vagância'
  },
  {
    key: 'sage',
    name: 'Sábio',
    nameEn: 'The Sage',
    motto: 'A verdade libertará você',
    color: '#dbeafe',
    icon: '📚',
    focus: ['intellectual', 'mental'],
    description: 'Busca verdade através de conhecimento e análise',
    fullDescription: 'O Sábio usa inteligência e análise para compreender o mundo. Acredita que a verdade pode ser encontrada através de pesquisa, estudo e reflexão. É um pensador, filósofo ou mentor que busca compartilhar conhecimento para iluminar o mundo.',
    strengths: ['Sabedoria', 'Inteligência', 'Expertise', 'Pensamento crítico', 'Discernimento'],
    weaknesses: ['Pode estudar sem agir', 'Distanciamento', 'Dogmatismo', 'Arrogância'],
    desire: 'Encontrar a verdade',
    fear: 'Ser enganado ou ignorante',
    strategy: 'Buscar informação e conhecimento',
    gift: 'Sabedoria e verdade',
    shadow: 'Distanciamento e julgamento'
  },
  {
    key: 'hero',
    name: 'Herói',
    nameEn: 'The Hero',
    motto: 'Onde há vontade, há um caminho',
    color: '#fecaca',
    icon: '⚔️',
    focus: ['physical', 'professional'],
    description: 'Prova seu valor através de coragem e ação',
    fullDescription: 'O Herói busca provar seu valor através de atos corajosos e difíceis. É determinado, competitivo e focado em fazer a diferença no mundo. Não foge dos desafios, mas os enfrenta de frente, inspirando outros com sua coragem e determinação.',
    strengths: ['Coragem', 'Perseverança', 'Competência', 'Disciplina', 'Determinação'],
    weaknesses: ['Arrogância', 'Necessidade de vitória', 'Imprudência', 'Inflexibilidade'],
    desire: 'Provar seu valor através da ação',
    fear: 'Fraqueza, vulnerabilidade',
    strategy: 'Ser forte e competente',
    gift: 'Coragem e disciplina',
    shadow: 'Necessidade de sempre vencer'
  },
  {
    key: 'outlaw',
    name: 'Fora da Lei',
    nameEn: 'The Outlaw',
    motto: 'Regras são feitas para serem quebradas',
    color: '#1f2937',
    icon: '🔥',
    focus: ['personal', 'cultural'],
    description: 'Busca revolução e libertação das estruturas',
    fullDescription: 'O Fora da Lei questiona o status quo e não aceita regras que considera injustas. Busca destruir o que não funciona para criar algo melhor. É um revolucionário, rebelde ou agente de mudança radical que não tem medo de chocar ou perturbar.',
    strengths: ['Liberdade radical', 'Coragem de quebrar regras', 'Liderança revolucionária'],
    weaknesses: ['Crime', 'Comportamento destrutivo', 'Autodestruição', 'Excesso'],
    desire: 'Vingança ou revolução',
    fear: 'Ser impotente ou ineficaz',
    strategy: 'Destruir, chocar ou revolucionar',
    gift: 'Libertação radical',
    shadow: 'Destrutividade sem propósito'
  },
  {
    key: 'magician',
    name: 'Mago',
    nameEn: 'The Magician',
    motto: 'Eu faço acontecer',
    color: '#c4b5fd',
    icon: '✨',
    focus: ['spiritual', 'intellectual'],
    description: 'Transforma realidade através de visão e conhecimento',
    fullDescription: 'O Mago entende as leis fundamentais do universo e as usa para manifestar visões em realidade. É um visionário, catalisador, inventor ou carismático que transforma situações, pessoas e até a si mesmo.',
    strengths: ['Encontrar soluções win-win', 'Visão', 'Carisma', 'Transformação', 'Catalisação'],
    weaknesses: ['Manipulação', 'Desconexão da realidade', 'Uso indevido de poder'],
    desire: 'Entender as leis fundamentais do universo',
    fear: 'Consequências negativas não intencionais',
    strategy: 'Desenvolver visão e vivê-la',
    gift: 'Transformação e manifestação',
    shadow: 'Manipulação e obsessão por poder'
  },
  {
    key: 'everyman',
    name: 'Cara Comum',
    nameEn: 'The Everyman',
    motto: 'Todos são criados iguais',
    color: '#e5e7eb',
    icon: '🤝',
    focus: ['personal', 'mental'],
    description: 'Busca pertencimento e conexão autêntica',
    fullDescription: 'O Cara Comum quer simplesmente pertencer. Valoriza conexão, realismo e trabalho duro. É o arquétipo da pessoa comum que encontra valor em ser parte de um grupo, comunidade ou sociedade.',
    strengths: ['Realismo', 'Empatia', 'Falta de pretensão', 'Solidez', 'Confiabilidade'],
    weaknesses: ['Perder identidade', 'Superficialidade', 'Passividade', 'Medo de se destacar'],
    desire: 'Conexão e pertencimento',
    fear: 'Ser excluído ou ficar de fora',
    strategy: 'Desenvolver virtudes comuns',
    gift: 'Realismo e empatia',
    shadow: 'Conformismo e perda de identidade'
  },
  {
    key: 'lover',
    name: 'Amante',
    nameEn: 'The Lover',
    motto: 'Você é o único',
    color: '#fce7f3',
    icon: '💕',
    focus: ['personal', 'cultural'],
    description: 'Busca intimidade e experiências sensoriais',
    fullDescription: 'O Amante busca intimidade e experiências sensoriais. Valoriza beleza, romance e conexão profunda. Este arquétipo encontra sentido através do amor - pelo trabalho, pessoas, experiências e vida em si.',
    strengths: ['Paixão', 'Gratidão', 'Apreciação', 'Compromisso', 'Beleza'],
    weaknesses: ['Obsessão', 'Ciúme', 'Perda de identidade', 'Dependência emocional'],
    desire: 'Intimidade e experiência',
    fear: 'Ficar sozinho, ser indesejado',
    strategy: 'Tornar-se atraente física e emocionalmente',
    gift: 'Paixão e gratidão',
    shadow: 'Obsessão e dependência'
  },
  {
    key: 'jester',
    name: 'Bobo da Corte',
    nameEn: 'The Jester',
    motto: 'Você só vive uma vez',
    color: '#fef08a',
    icon: '🎭',
    focus: ['cultural', 'mental'],
    description: 'Vive o momento com alegria e leveza',
    fullDescription: 'O Bobo da Corte vive no momento, trazendo alegria e leveza para o mundo. Usa humor para conectar, curar e iluminar verdades difíceis. Este arquétipo lembra que a vida deve ser apreciada e divertida.',
    strengths: ['Alegria', 'Leveza', 'Humor', 'Viver no momento', 'Irreverência positiva'],
    weaknesses: ['Frivolidade', 'Irresponsabilidade', 'Crueldade através do humor'],
    desire: 'Viver no momento com alegria',
    fear: 'Tédio ou ser chato',
    strategy: 'Brincar, fazer piadas, ser engraçado',
    gift: 'Alegria e perspectiva',
    shadow: 'Evasão e irresponsabilidade'
  },
  {
    key: 'caregiver',
    name: 'Cuidador',
    nameEn: 'The Caregiver',
    motto: 'Ame seu próximo como a si mesmo',
    color: '#bbf7d0',
    icon: '🌱',
    focus: ['personal', 'spiritual'],
    description: 'Protege e cuida dos outros com compaixão',
    fullDescription: 'O Cuidador é movido por compaixão e desejo de ajudar os outros. É generoso, cuidadoso e protetor. Este arquétipo encontra satisfação em fazer a diferença na vida das pessoas ao seu redor.',
    strengths: ['Compaixão', 'Generosidade', 'Cuidado', 'Proteção', 'Abnegação'],
    weaknesses: ['Martírio', 'Sufocamento', 'Ser explorado', 'Culpa'],
    desire: 'Proteger e cuidar dos outros',
    fear: 'Egoísmo e ingratidão',
    strategy: 'Fazer coisas pelos outros',
    gift: 'Compaixão e generosidade',
    shadow: 'Martírio e sufocamento'
  },
  {
    key: 'creator',
    name: 'Criador',
    nameEn: 'The Creator',
    motto: 'Se pode ser imaginado, pode ser criado',
    color: '#fbcfe8',
    icon: '🎨',
    focus: ['intellectual', 'cultural'],
    description: 'Cria valor duradouro através de inovação',
    fullDescription: 'O Criador é impulsionado pela necessidade de criar algo de valor duradouro. É imaginativo, inovador e busca auto-expressão através da criação. Acredita que se algo pode ser imaginado, pode ser criado.',
    strengths: ['Criatividade', 'Imaginação', 'Inovação', 'Auto-expressão', 'Visão artística'],
    weaknesses: ['Perfeccionismo', 'Criatividade bloqueada', 'Drama desnecessário'],
    desire: 'Criar algo de valor duradouro',
    fear: 'Mediocridade, visão defeituosa',
    strategy: 'Desenvolver controle e habilidade artística',
    gift: 'Criatividade e inovação',
    shadow: 'Perfeccionismo paralisante'
  },
  {
    key: 'ruler',
    name: 'Governante',
    nameEn: 'The Ruler',
    motto: 'O poder não é tudo, é a única coisa',
    color: '#fcd34d',
    icon: '👑',
    focus: ['professional', 'intellectual'],
    description: 'Exerce controle e cria ordem do caos',
    fullDescription: 'O Governante busca criar prosperidade e sucesso para sua comunidade ou família. Assume responsabilidade, lidera com autoridade e cria estruturas que funcionam. Valoriza controle, ordem e legado.',
    strengths: ['Liderança', 'Responsabilidade', 'Ordem', 'Status', 'Recursos'],
    weaknesses: ['Autoritarismo', 'Incapacidade de delegar', 'Comportamento tirânico'],
    desire: 'Controle e sucesso',
    fear: 'Caos, ser derrubado',
    strategy: 'Exercer liderança',
    gift: 'Responsabilidade e ordem',
    shadow: 'Tirania e rigidez'
  }
];

export const getArchetypeByKey = (key) => ARCHETYPES.find(a => a.key === key);

// Human Design Types
export const HD_TYPES = [
  {
    key: 'generator',
    name: 'Gerador',
    nameEn: 'Generator',
    strategy: 'Responder',
    strategyEn: 'To Respond',
    authority: 'Sacral',
    percentage: '37%',
    color: '#ef4444',
    description: 'Força de trabalho do planeta. Energia sustentável quando responde ao que ama.',
    gutCheckPrompt: 'Você sente excitação genuína? Seu corpo responde com um "SIM" visceral?',
    notSelfTheme: 'Frustração'
  },
  {
    key: 'manifesting_generator',
    name: 'Gerador Manifestante',
    nameEn: 'Manifesting Generator',
    strategy: 'Responder e Informar',
    strategyEn: 'To Respond & Inform',
    authority: 'Sacral',
    percentage: '33%',
    color: '#f97316',
    description: 'Multi-apaixonado. Pula etapas naturalmente quando segue a resposta sacral.',
    gutCheckPrompt: 'Visualize o resultado. Isso acende algo em você? Sente pressa ou resposta genuína?',
    notSelfTheme: 'Frustração e Raiva'
  },
  {
    key: 'projector',
    name: 'Projetor',
    nameEn: 'Projector',
    strategy: 'Aguardar o Convite',
    strategyEn: 'Wait for the Invitation',
    authority: 'Varies',
    percentage: '20%',
    color: '#3b82f6',
    description: 'Guias naturais. Veem profundamente os outros quando reconhecidos.',
    gutCheckPrompt: 'Você foi convidado ou reconhecido para isso? Este é um convite genuíno para seus talentos?',
    notSelfTheme: 'Amargura'
  },
  {
    key: 'manifestor',
    name: 'Manifestador',
    nameEn: 'Manifestor',
    strategy: 'Informar',
    strategyEn: 'To Inform',
    authority: 'Emotional/Splenic',
    percentage: '8%',
    color: '#8b5cf6',
    description: 'Iniciadores. Impactam o mundo quando informam antes de agir.',
    gutCheckPrompt: 'Isso vem de um impulso interno claro? Você informou os que serão afetados?',
    notSelfTheme: 'Raiva'
  },
  {
    key: 'reflector',
    name: 'Refletor',
    nameEn: 'Reflector',
    strategy: 'Esperar Ciclo Lunar',
    strategyEn: 'Wait a Lunar Cycle',
    authority: 'Lunar',
    percentage: '1%',
    color: '#06b6d4',
    description: 'Espelhos da comunidade. Sabedoria única quando dão tempo às decisões.',
    gutCheckPrompt: 'Você esperou um ciclo lunar (28 dias) para decidir sobre decisões importantes?',
    notSelfTheme: 'Decepção'
  }
];

export const getHDTypeByKey = (key) => HD_TYPES.find(t => t.key === key);

// Zodiac Signs
export const ZODIAC_SIGNS = [
  { key: 'aries', name: 'Áries', symbol: '♈', element: 'fire', dates: '21/03 - 19/04' },
  { key: 'taurus', name: 'Touro', symbol: '♉', element: 'earth', dates: '20/04 - 20/05' },
  { key: 'gemini', name: 'Gêmeos', symbol: '♊', element: 'air', dates: '21/05 - 20/06' },
  { key: 'cancer', name: 'Câncer', symbol: '♋', element: 'water', dates: '21/06 - 22/07' },
  { key: 'leo', name: 'Leão', symbol: '♌', element: 'fire', dates: '23/07 - 22/08' },
  { key: 'virgo', name: 'Virgem', symbol: '♍', element: 'earth', dates: '23/08 - 22/09' },
  { key: 'libra', name: 'Libra', symbol: '♎', element: 'air', dates: '23/09 - 22/10' },
  { key: 'scorpio', name: 'Escorpião', symbol: '♏', element: 'water', dates: '23/10 - 21/11' },
  { key: 'sagittarius', name: 'Sagitário', symbol: '♐', element: 'fire', dates: '22/11 - 21/12' },
  { key: 'capricorn', name: 'Capricórnio', symbol: '♑', element: 'earth', dates: '22/12 - 19/01' },
  { key: 'aquarius', name: 'Aquário', symbol: '♒', element: 'air', dates: '20/01 - 18/02' },
  { key: 'pisces', name: 'Peixes', symbol: '♓', element: 'water', dates: '19/02 - 20/03' }
];

export const getZodiacByKey = (key) => ZODIAC_SIGNS.find(z => z.key === key);